apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2-test-deployment-4
  namespace: db2-test-5
  labels:
    app: db2-test-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2-test-5
  template:
    metadata:
      labels:
        app: db2-test-5
    spec:
      serviceAccountName: db2-sa
      containers:
        - name: db2-container
          image: docker.io/ibmcom/db2:11.5.4.0
          ports:
            - containerPort: 50000
              name: db2-port
          env:
            - name: LICENSE
              value: "accept"
            - name: DB2INST1_PASSWORD
              value: "test"
            - name: DBNAME
              value: "testdb"
            - name: PERSISTENT_HOME
              value: "true"
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - mountPath: /database
              name: db2-storage
            - mountPath: /backup
              name: s3-backup-storage
          securityContext:
            fsGroup: 0
            runAsNonRoot: false
            privileged: true
      volumes:
        - name: db2-storage
          persistentVolumeClaim:
            claimName: pvc-db2-4
        - name: s3-backup-storage
          persistentVolumeClaim:
            claimName: test-cos